pipeline{
    agent any
    tools {
        jdk 'java-17'
        maven 'maven'
    }
    stages{
        stage('Git checkout'){
            steps{
                git branch: 'feature-xyz', url: 'https://github.com/learningdevops77/test-1.git'
            }
        }
    
        stage('Build'){
            steps{
                sh 'mvn clean install'
            }
        }
        stage('Compile'){
            steps{
                sh 'mvn compile'
            }
        }
        stage('Building-DockerImage'){
            steps{
                sh 'docker build -t manojkrishnappa/continous-intergartion:1 .'
            }
        }
        stage('Contianersation'){
            steps{
            sh '''
                docker stop c1 || true
                docker rm c1 || true
                docker run -it -d --name c1 -p 9000:8080 manojkrishnappa/continous-intergartion:1
            ''' 
            }
        }

        stage('Login to Docker Hub') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                        sh "echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin"
                    }
                }
            }
        }

            stage('Pushing image to repository') {
            steps {
                sh 'docker push manojkrishnappa/webapp:1'
            }
        }

        }

    }
